[project]
name = "tds-proj1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "flask>=3.1.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
